### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/loanpy#24]
Earlier I was unconsciously always installing the latest stable version from pypi and running the tests against that, locally, instead of installing the latest commit from github. This issue was fixed in #21. However, now I can see that the first minor change that I had announced in https://github.com/martino-vic/loanpy/issues/18#issuecomment-1164553728, i.e. https://github.com/martino-vic/loanpy/commit/c44ecfc5032a0f4a9582eed285fce95a03362098 in fact broke quite a few tests. These need to be fixed now.

**Comment by martino-vic** [comment]
unittests for helpers.py running: 53c143326112465e805546bef1ef5ff19c710831

**Comment by martino-vic** [comment]
I had assumed that the input-type for prosodic_string is the same as for word2phonotactics, but no: While latter took a string, the former needs a tuple or list:

```
>>> from lingpy import prosodic_string as p
>>> p('xyz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 881, in prosodic_string
    [int(t) for t in tokens2class(string, rcParams['art'],
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 782, in tokens2class
    raise ValueError("[!] Need tuple or list as input.")
ValueError: [!] Need tuple or list as input.
>>> p('x y z')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 881, in prosodic_string
    [int(t) for t in tokens2class(string, rcParams['art'],
  File "/home/viktor/Documents/cldfvenv3.9/lib/python3.9/site-packages/lingpy/sequence/sound_classes.py", line 782, in tokens2class
    raise ValueError("[!] Need tuple or list as input.")
ValueError: [!] Need tuple or list as input.
>>> p(list('xyz'))
'AXN'
```

I can fix this only by changing the source code. The problem lies in [helpers.py line 615](https://github.com/martino-vic/loanpy/blob/2.0-beta/src/loanpy/helpers.py#L615). `self.forms_target_language` needs to be changed, so that instead of being a word list of the type `["abc", "def", "ghi"]` it should be  `[["a", "b", "c"], ["d", "e", "f"], ["g", "h", "i"]]`, i.e.  `[i.split(" ") for i in ["a b c", "d e f", "g h i"]]`

**Comment by martino-vic** [comment]
Careful: I'm making local changes in the virtual environment's loanpy folder but am pushing to GitHub from the GitHub folder. I have to remember copying changes before pushing.

**Comment by martino-vic** [comment]
Fixed in commit ca23d2868a117ae3ad03b242955273e085c9f959
